name: publish to nuget
on:
  [push]
jobs:
    Nuget-publish:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup .NET Core @ Latest
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
        
        - name: Run ProjectBuild
          env: 
            NUGET_KEY : {secrets.NUGET_KEY}
          run: | 
            dotnet run --project ProjectBuild/ProjectBuild.csproj
