name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
    Nuget-publish:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup .NET Core @ Latest
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.0.x'
        
        - name: Run ProjectBuild
          run: dotnet run --project ProjectBuild/ProjectBuild.csproj
          env: 
            NUGET_KEY : ${{secrets.NUGET_KEY}}
